# Generated by Django 2.2.8 on 2020-02-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20200215_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
