# Generated by Django 2.2.8 on 2020-02-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20200215_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='html_body',
        ),
    ]
