# Generated by Django 2.2.8 on 2020-02-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_remove_post_html_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='message',
        ),
    ]
